spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://y:6543/ears3
    username: ears
    password: ears
    test-on-borrow: true
    validationQuery: SELECT 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.EJB3NamingStrategy
    defer-datasource-initialization: true

  mvc:
    static-path-pattern: /resources/**

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    org:
      springframework:
        web: DEBUG

java:
  util:
    logging:
      SimpleFormatter:
        format: "%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$-6s %2$s %5$s%6$s%n"

server:
  port: 8081
  servlet:
    context-path: /ears3


ears:
  platform: SDN:C17::11BU
  send-events-to: http://replace.me
  navigation:
    server: http://replace.me
  csr:
    license: UN
  ontology:
    username: earsontology
    password: REPLACEME
  read-only: false
  program:
    regex: "202[6-9]"