CREATE TABLE country (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    term_id bigint NOT NULL
);

CREATE TABLE cruise (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data_url character varying(255),
    end_date timestamp without time zone,
    final_report_url character varying(255),
    identifier character varying(100) NOT NULL,
    is_cancelled boolean NOT NULL,
    name character varying(255),
    objectives character varying(7500),
    planning_url character varying(255),
    purpose character varying(255),
    start_date timestamp without time zone,
    track_gml_url character varying(255),
    track_image_url character varying(255),
    arrival_harbour_id bigint NOT NULL,
    collate_centre_id bigint NOT NULL,
    departure_harbour_id bigint NOT NULL,
    platform_id bigint NOT NULL
);

CREATE TABLE cruise_chief_scientists (
    cruise_id bigint NOT NULL,
    chief_scientist_id bigint NOT NULL
);

CREATE TABLE cruise_p02 (
    cruise_id bigint NOT NULL,
    p02_id bigint NOT NULL
);

CREATE TABLE cruise_programs (
    cruise_id bigint NOT NULL,
    program_id bigint NOT NULL
);

CREATE TABLE cruise_sea_areas (
    cruise_id bigint NOT NULL,
    sea_areas_id bigint NOT NULL
);

CREATE TABLE event (
    dtype character varying(31) NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    creation_time timestamp without time zone,
    event_definition_id character varying(255),
    identifier character varying(255),
    modification_time timestamp without time zone,
    time_stamp timestamp without time zone,
    action_id bigint NOT NULL,
    actor_id bigint,
    platform_id bigint NOT NULL,
    process_id bigint NOT NULL,
    program_id bigint,
    subject_id bigint NOT NULL,
    tool_id bigint NOT NULL,
    tool_category_id bigint NOT NULL,
    label character varying(100),
    description character varying(1000),
    station character varying(100)
);

CREATE TABLE event_navigation (
    event_id bigint NOT NULL,
    navigation_id bigint NOT NULL
);

CREATE TABLE event_properties (
    event_id bigint NOT NULL,
    properties_id bigint NOT NULL
);

CREATE TABLE event_thermosal (
    event_id bigint NOT NULL,
    thermosal_id bigint NOT NULL
);

CREATE TABLE event_weather (
    event_id bigint NOT NULL,
    weather_id bigint NOT NULL
);

CREATE TABLE harbour (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    country_id bigint,
    term_id bigint NOT NULL
);

CREATE TABLE license (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    term_id bigint
);

CREATE TABLE linked_data_term (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    identifier character varying(100) NOT NULL,
    name character varying(256) NOT NULL,
    transitive_identifier character varying(100),
    transitive_urn character varying(100),
    urn character varying(100)
);

CREATE TABLE navigation (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    instrument_time timestamp with time zone,
    time_stamp timestamp with time zone,
    cog double precision,
    depth double precision,
    heading double precision,
    lat double precision,
    lon double precision,
    sog double precision,
    sow double precision
);

CREATE TABLE organisation (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city character varying(255),
    delivery_point character varying(255),
    email_address character varying(255),
    fax_number character varying(255),
    phone_number character varying(255),
    postal_code character varying(255),
    website character varying(255),
    country_id bigint,
    term_id bigint NOT NULL
);

CREATE TABLE person (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email character varying(255),
    fax_number character varying(255),
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    phone_number character varying(255),
    organisation_id bigint
);

CREATE TABLE platform (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    platform_class_id bigint,
    term_id bigint NOT NULL,
    vessel_operator_id bigint
);

CREATE TABLE program (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description character varying(4000),
    identifier character varying(255) NOT NULL,
    name character varying(255),
    sampling character varying(2000)
);

CREATE TABLE program_principal_investigators (
    program_id bigint NOT NULL,
    principal_investigators_id bigint NOT NULL
);
CREATE TABLE program_projects (
    program_id bigint NOT NULL,
    projects_id bigint NOT NULL
);
CREATE TABLE project (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    term_id bigint NOT NULL
);

CREATE TABLE property (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uom character varying(255),
    "value" character varying(255),
    key_id bigint NOT NULL
);

CREATE TABLE sea_area (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    east_bound_longitude double precision,
    north_bound_latitude double precision,
    south_bound_latitude double precision,
    west_bound_longitude double precision,
    term_id bigint NOT NULL
);

CREATE TABLE thermosal (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    instrument_time timestamp with time zone,
    time_stamp timestamp with time zone,
    conductivity double precision,
    raw_fluorometry double precision,
    salinity double precision,
    sigmat double precision,
    temperature double precision
);

CREATE TABLE tool (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_term_id bigint,
    term_id bigint NOT NULL
);

CREATE TABLE weather (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    instrument_time timestamp with time zone,
    time_stamp timestamp with time zone,
    atmospheric_pressure double precision,
    atmospheric_temperature double precision,
    humidity double precision,
    solar_radiation double precision,
    water_temperature double precision,
    wind_direction double precision,
    wind_speed_average double precision,
    wind_speed_instantaneous double precision
);

ALTER TABLE country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);
ALTER TABLE cruise
    ADD CONSTRAINT cruise_pkey PRIMARY KEY (id);
ALTER TABLE event
    ADD CONSTRAINT event_pkey PRIMARY KEY (id);
ALTER TABLE harbour
    ADD CONSTRAINT harbour_pkey PRIMARY KEY (id);
ALTER TABLE license
    ADD CONSTRAINT license_pkey PRIMARY KEY (id);
ALTER TABLE linked_data_term
    ADD CONSTRAINT linked_data_term_pkey PRIMARY KEY (id);
ALTER TABLE navigation
    ADD CONSTRAINT navigation_pkey PRIMARY KEY (id);
ALTER TABLE organisation
    ADD CONSTRAINT organisation_pkey PRIMARY KEY (id);
ALTER TABLE person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);
ALTER TABLE platform
    ADD CONSTRAINT platform_pkey PRIMARY KEY (id);
ALTER TABLE program
    ADD CONSTRAINT program_pkey PRIMARY KEY (id);
ALTER TABLE project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id);
ALTER TABLE property
    ADD CONSTRAINT property_pkey PRIMARY KEY (id);
ALTER TABLE sea_area
    ADD CONSTRAINT sea_area_pkey PRIMARY KEY (id);
ALTER TABLE thermosal
    ADD CONSTRAINT thermosal_pkey PRIMARY KEY (id);
ALTER TABLE tool
    ADD CONSTRAINT tool_pkey PRIMARY KEY (id);
ALTER TABLE tool
    ADD CONSTRAINT uk5t3r8cloglmcymweq9ia322l3 UNIQUE (term_id, parent_term_id);
ALTER TABLE platform
    ADD CONSTRAINT uk_2sej6mjan2797xigopv2blrqf UNIQUE (term_id);
ALTER TABLE harbour
    ADD CONSTRAINT uk_2v5o3wq6fi566kv7wnv6f4aq UNIQUE (term_id);
ALTER TABLE event_properties
    ADD CONSTRAINT uk_452m44l3xum1rcgbwhvr2eau4 UNIQUE (properties_id);
ALTER TABLE linked_data_term
    ADD CONSTRAINT uk_8q3am3olp9c3xme5cwm24vuw3 UNIQUE (identifier);
ALTER TABLE tool
    ADD CONSTRAINT uk_9sfjqmclw0bqnaeesk60j7pea UNIQUE (term_id);
ALTER TABLE organisation
    ADD CONSTRAINT uk_cu3k9cqi9vj3wfg9fbi08ys4x UNIQUE (term_id);
ALTER TABLE project
    ADD CONSTRAINT uk_dp8mk8pblhl4mtydeikb7e1qp UNIQUE (term_id);
ALTER TABLE cruise
    ADD CONSTRAINT uk_fm2el3cesydw4smkckhbaspfx UNIQUE (identifier);
ALTER TABLE linked_data_term
    ADD CONSTRAINT uk_g2mqju57whiiqss0d5xbx7s92 UNIQUE (urn);
ALTER TABLE sea_area
    ADD CONSTRAINT uk_gqr2dm2qe579i35pkr0053gk2 UNIQUE (term_id);
ALTER TABLE program
    ADD CONSTRAINT uk_h2vlfxbs3233768m6ohxfjoig UNIQUE (identifier);
ALTER TABLE country
    ADD CONSTRAINT uk_tjesoaoodieycpek6y1he4hcl UNIQUE (term_id);
ALTER TABLE person
    ADD CONSTRAINT ukh36v1mgchbyio7nbvp88efccd UNIQUE (first_name, last_name, organisation_id);
ALTER TABLE weather
    ADD CONSTRAINT weather_pkey PRIMARY KEY (id);
CREATE INDEX linked_data_term_identifier_idx ON linked_data_term USING btree (identifier);
CREATE INDEX linked_data_term_name_idx ON linked_data_term USING btree (name);
CREATE INDEX linked_data_term_urn_idx ON linked_data_term USING btree (urn);
CREATE INDEX navigation_time_stamp_idx ON navigation USING btree (time_stamp, instrument_time);
CREATE INDEX thermosal_instrument_time_idx ON thermosal USING btree (instrument_time, time_stamp);
CREATE INDEX weather_instrument_time_idx ON weather USING btree (instrument_time, time_stamp);
ALTER TABLE event_properties
    ADD CONSTRAINT fk1cjaoimvy0nt2fvx2axqbmf89 FOREIGN KEY (event_id) REFERENCES event(id);
ALTER TABLE property
    ADD CONSTRAINT fk1h72bwotlbm9s1h017b956sju FOREIGN KEY (key_id) REFERENCES linked_data_term(id);
ALTER TABLE event_properties
    ADD CONSTRAINT fk1umw2gdcbx6r0tt8o8xfjdccc FOREIGN KEY (properties_id) REFERENCES property(id);
ALTER TABLE event_navigation
    ADD CONSTRAINT fk3g17dr03sfpdipkl8noeht2tj FOREIGN KEY (event_id) REFERENCES event(id);
ALTER TABLE platform
    ADD CONSTRAINT fk3itfleyv1rdt665vkdf1fxks FOREIGN KEY (term_id) REFERENCES linked_data_term(id);
ALTER TABLE event_thermosal
    ADD CONSTRAINT fk51u8aiqcdq3s7uqe7pc4nmj17 FOREIGN KEY (event_id) REFERENCES event(id);
ALTER TABLE cruise
    ADD CONSTRAINT fk5787bwyon23wdxx6ns08c6b1l FOREIGN KEY (platform_id) REFERENCES platform(id);
ALTER TABLE cruise_sea_areas
    ADD CONSTRAINT fk5mkx4g6vkyd44a4m3wigcwo5y FOREIGN KEY (cruise_id) REFERENCES cruise(id);
ALTER TABLE cruise
    ADD CONSTRAINT fk5u9e0gs4h59wnwts3r8og76fk FOREIGN KEY (departure_harbour_id) REFERENCES harbour(id);
ALTER TABLE sea_area
    ADD CONSTRAINT fk600t2twtkss92sdm96lslyaqo FOREIGN KEY (term_id) REFERENCES linked_data_term(id);
ALTER TABLE tool
    ADD CONSTRAINT fk62ggagfnuqpoqkgugowbs6v34 FOREIGN KEY (parent_term_id) REFERENCES linked_data_term(id);
ALTER TABLE cruise_sea_areas
    ADD CONSTRAINT fk6e9ys4yluiy7h8i5rikb4qhgg FOREIGN KEY (sea_areas_id) REFERENCES sea_area(id);
ALTER TABLE program_projects
    ADD CONSTRAINT fk6hmok13takxy2d7hemytjm5p0 FOREIGN KEY (program_id) REFERENCES program(id);
ALTER TABLE event
    ADD CONSTRAINT fk6p2sehrpn6gwaxqnqwdd4b6gx FOREIGN KEY (subject_id) REFERENCES linked_data_term(id);
ALTER TABLE cruise
    ADD CONSTRAINT fk6v7qd7wuxfah8lo1js0nwtw5f FOREIGN KEY (arrival_harbour_id) REFERENCES harbour(id);
ALTER TABLE cruise_p02
    ADD CONSTRAINT fk7ak96j2vexvehvkn0c86u4iif FOREIGN KEY (cruise_id) REFERENCES cruise(id);
ALTER TABLE event
    ADD CONSTRAINT fk7hgji3q7nnjbffouyd1foira2 FOREIGN KEY (platform_id) REFERENCES platform(id);
ALTER TABLE event_thermosal
    ADD CONSTRAINT fk806tis8759ie57fhwxibh847e FOREIGN KEY (thermosal_id) REFERENCES thermosal(id);
ALTER TABLE person
    ADD CONSTRAINT fkb4byuy8j1cq0q8jk0qgnjwbsn FOREIGN KEY (organisation_id) REFERENCES organisation(id);
ALTER TABLE project
    ADD CONSTRAINT fkci82rpc0qdxyuvjk41n9pas7s FOREIGN KEY (term_id) REFERENCES linked_data_term(id);
ALTER TABLE organisation
    ADD CONSTRAINT fke11xjrjhg8d9wubccbjjtcxeg FOREIGN KEY (term_id) REFERENCES linked_data_term(id);
ALTER TABLE event
    ADD CONSTRAINT fke655lmx2uldxuqfssqarl037w FOREIGN KEY (actor_id) REFERENCES person(id);
ALTER TABLE program_principal_investigators
    ADD CONSTRAINT fkg3i41wtxcl15r8lckynghnxex FOREIGN KEY (principal_investigators_id) REFERENCES person(id);
ALTER TABLE program_projects
    ADD CONSTRAINT fkgl46hg6xkuvw7xmxiqt66s27m FOREIGN KEY (projects_id) REFERENCES project(id);
ALTER TABLE event
    ADD CONSTRAINT fkgn98hdg55f5rdrkvqx74jbogy FOREIGN KEY (tool_category_id) REFERENCES linked_data_term(id);
ALTER TABLE harbour
    ADD CONSTRAINT fkgtn5wnucagd1596fe5duxbrlg FOREIGN KEY (country_id) REFERENCES country(id);
ALTER TABLE harbour
    ADD CONSTRAINT fkh17m0e62n4itmo499bp2s4t2c FOREIGN KEY (term_id) REFERENCES linked_data_term(id);
ALTER TABLE platform
    ADD CONSTRAINT fkhqa3fwu4ooeh8jjdsr6sme2kk FOREIGN KEY (vessel_operator_id) REFERENCES organisation(id);
ALTER TABLE tool
    ADD CONSTRAINT fkhsjqunngaqhpcrjathv0nl8i5 FOREIGN KEY (term_id) REFERENCES linked_data_term(id);
ALTER TABLE event_weather
    ADD CONSTRAINT fkig82qek9mv49qndlwqi6kpfmo FOREIGN KEY (weather_id) REFERENCES weather(id);
ALTER TABLE organisation
    ADD CONSTRAINT fkis5edbq32h4xbyupuiufk0rpu FOREIGN KEY (country_id) REFERENCES country(id);
ALTER TABLE event
    ADD CONSTRAINT fkk6cy5mwl67rn23mughnsnlwql FOREIGN KEY (program_id) REFERENCES program(id);
ALTER TABLE program_principal_investigators
    ADD CONSTRAINT fkl32qxkd4l6ai9b5cqr01uxeot FOREIGN KEY (program_id) REFERENCES program(id);
ALTER TABLE cruise
    ADD CONSTRAINT fkl4mvslpjnj6ehug33qk82jwtm FOREIGN KEY (collate_centre_id) REFERENCES organisation(id);
ALTER TABLE cruise_chief_scientists
    ADD CONSTRAINT fklircj22tgmqkecjnf247rsavx FOREIGN KEY (chief_scientist_id) REFERENCES person(id);
ALTER TABLE cruise_p02
    ADD CONSTRAINT fkno6tk6fadwcsqtxa85fvb9i8t FOREIGN KEY (p02_id) REFERENCES linked_data_term(id);
ALTER TABLE event
    ADD CONSTRAINT fko6dykgjt75k3bm0323q518g4h FOREIGN KEY (action_id) REFERENCES linked_data_term(id);
ALTER TABLE platform
    ADD CONSTRAINT fkpqrffeqjdnlsv7loio77o5ga6 FOREIGN KEY (platform_class_id) REFERENCES linked_data_term(id);
ALTER TABLE cruise_programs
    ADD CONSTRAINT fkqfgkh5flh7wck34wfc4smermv FOREIGN KEY (program_id) REFERENCES program(id);
ALTER TABLE country
    ADD CONSTRAINT fkrcjl8ddhppnhmvvuiudxh86e7 FOREIGN KEY (term_id) REFERENCES linked_data_term(id);
ALTER TABLE event
    ADD CONSTRAINT fkrlboxvob1nt61buq8srr56wbx FOREIGN KEY (tool_id) REFERENCES tool(id);
ALTER TABLE license
    ADD CONSTRAINT fksf1ukvdd64ta17eb99fmciiy3 FOREIGN KEY (term_id) REFERENCES linked_data_term(id);
ALTER TABLE cruise_chief_scientists
    ADD CONSTRAINT fksf8q6mkkr5ttlrbbmrqpnr7n5 FOREIGN KEY (cruise_id) REFERENCES cruise(id);
ALTER TABLE event
    ADD CONSTRAINT fkshrqekmn14qk9ly8axv140tam FOREIGN KEY (process_id) REFERENCES linked_data_term(id);
ALTER TABLE event_navigation
    ADD CONSTRAINT fkt09p2wbpqf10o53n3wto7oj5d FOREIGN KEY (navigation_id) REFERENCES navigation(id);
ALTER TABLE cruise_programs
    ADD CONSTRAINT fkth5rxmvbxmqial3g41sw9lm2l FOREIGN KEY (cruise_id) REFERENCES cruise(id);
ALTER TABLE event_weather
    ADD CONSTRAINT fkto3fa6ecf9qais3acg8yu23s1 FOREIGN KEY (event_id) REFERENCES event(id);